version: '3.8'

services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: template-nuxt:latest
    container_name: template-nuxt-app
    ports:
      - "8080:80"
    env_file:
      - .env.docker
    restart: unless-stopped
    depends_on: []

networks:
  default:
    name: nuxt-network
    driver: bridge